name: 'Publish package'
on:
  push:
    branches:
      - main
    paths:
      - 'packages/design/**'
  workflow_dispatch:

jobs:
  release:
    name: "Package release 🎉"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: 'Installing node...'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g pnpm@latest

      - name: 'Installing dependencies...'
        run: pnpm install --frozen-lockfile --silent

      - name: 'Building and releasing package...'
        working-directory: packages/design
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
